// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_7OxCQzHHQEm09rnuNQln9hm5SsPFiE8',
    appId: '1:660048172699:web:84ad8a537e4fa34422183e',
    messagingSenderId: '660048172699',
    projectId: 'join-meds',
    authDomain: 'join-meds.firebaseapp.com',
    databaseURL: 'https://join-meds-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'join-meds.firebasestorage.app',
    measurementId: 'G-BQHNK9N3VE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTD906JaSBE8tQwzXIMBigSO9OsPlaNRY',
    appId: '1:660048172699:android:9275edfb319758b522183e',
    messagingSenderId: '660048172699',
    projectId: 'join-meds',
    databaseURL: 'https://join-meds-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'join-meds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4i4FjK9Cv6tVNlB-D-nx4YXZjnReHEkA',
    appId: '1:660048172699:ios:67a36a994c68244e22183e',
    messagingSenderId: '660048172699',
    projectId: 'join-meds',
    databaseURL: 'https://join-meds-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'join-meds.firebasestorage.app',
    iosBundleId: 'com.example.joinMeds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_7OxCQzHHQEm09rnuNQln9hm5SsPFiE8',
    appId: '1:660048172699:web:bf8ce721b7b549cc22183e',
    messagingSenderId: '660048172699',
    projectId: 'join-meds',
    authDomain: 'join-meds.firebaseapp.com',
    databaseURL: 'https://join-meds-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'join-meds.firebasestorage.app',
    measurementId: 'G-FYBX9H4M32',
  );

}