
import 'package:flutter/material.dart';
import '../../../constants/constant.dart';

class BScMLTDegreeOngoing extends StatefulWidget {
  const BScMLTDegreeOngoing({super.key});

  @override
  State<BScMLTDegreeOngoing> createState() => _BScMLTDegreeOngoingState();
}

class _BScMLTDegreeOngoingState extends State<BScMLTDegreeOngoing> {
  final TextEditingController _universityController = TextEditingController();
  String? _university;
  String? academicYear;

  final List<String> academicYears = [
    '1st Year',
    '2nd Year',
    '3rd Year',
    '4th Year',
  ];

  final List<String> universities = [
    'Andaman and Nicobar Islands Institute of Medical Sciences, Port Blair',
    'ASSAM MEDICAL COLLEGE, DIBRUGARH',
    'Fakhruddin Ali Ahmed Medical College, Barpeta',
    'A J Institute of Medical Sciences & Research Centre, Mangalore',
    'Aarupadai Veedu Medical College, Pondicherry',
    'Acharya Shri Chander College of Medical Sciences, Jammu',
    'ACPM Medical College, Dhule',
    'ACS Medical College and Hospital, Chennai',
    'ACSR Govt Medical College, Nellore',
    'Adesh Institute of Medical Sciences & Research, Bhatinda',
    'Adichunchanagiri Institute of Medical Sciences Bellur',
    'AGARTALA GOVT. MEDICAL COLLEGE, AGARTALA',
    'AHIRAMJEE JIJIBHAI MEDICAL COLLEGE, PUNE',
    'AIIMS Bathinda',
    'AIIMS Bilaspur Changar Palasiyan, Himachal Pradesh',
    'AIIMS Guahawti',
    'AIIMS Jammu',
    'AIIMS Mangalagiri',
    'AIIMS Rajkot',
    'AIIMS, Bhubaneswar',
    'AIIMS, Bibi Nagar, Hyderabad',
    'AIIMS, Deogarh',
    'AIIMS, Gorakhpur',
    'AIIMS, Jodhpur',
    'AIIMS, Kalyani',
    'AIIMS, Madurai',
    'AIIMS, Nagpur',
    'AIIMS, New Delhi',
    'AIIMS, Patna',
    'AIIMS, Rai Bareli',
    'AIIMS, Raipur',
    'AIIMS, Rishikesh',
    'AIIMS‐Bhopal',
    'Akash Institute of Medical Sciences & Research Centre, Devanhalli, Bangalore, Karnataka',
    'Al Falah School of Medical Sciences & Research Centre, Faridabad',
    'Al-Ameen Medical College, Bijapur',
    'Al-Azhar Medical College and Super Speciality Hospital, Thodupuzha',
    'Alluri Sitaram Raju Academy of Medical Sciences, Eluru',
    'Amala Institute of Medical Sciences, Thrissur',
    'Amaltas Institute of Medical Sciences, Dewas',
    'American International Institute of Medical Sciences, Bedwas',
    'Amrita School of Medicine, Elamkara, Kochi',
    'Ananta Institute of Medical Sciences & Research Centre, Rajsamand',
    'Andaman and Nicobar Islands Institute of Medical Sciences, Port Blair',
    'Andhra Medical College, Visakhapatnam',
    'Annapoorna Medical College & Hospital, Salem',
    'ANUGRAH NARAYAN MAGADH MEDICAL COLLEGE, GAYA',
    'Apollo Institute of Medical Sciences and Research, Chittoor',
    'Apollo Institute of Medical Sciences and Research, Hyderabad',
    'Army College of Medical Sciences, New Delhi',
    'Ashwini Rural Medical College, Hospital & Research Centre, Solapur',
    'ASSAM MEDICAL COLLEGE, DIBRUGARH',
    'ATAL BIHARI VAJPAYEE GMC, VIDISHA',
    'Atal Bihari Vajpayee IMS & DR RML HOSPITAL, NEW DELHI',
    'Autonomous State Medical College, Fatehpur',
    'Autonomous State Medical College, Etah',
    'Autonomous State Medical College Society, Mirzapur',
    'Autonomous State Medical College Society, Hardoi',
    'Autonomous State Medical College, Ghazipur',
    'Autonomous State Medical College, Pratapgarh',
    'Autonomous State Medical College, Siddharthnagar',
    'Ayaan Institute of Medical Sciences, Teaching Hospital & Research',
    "Centre, Kanaka Mamidi, R.R. Dist",
    "Azeezia Instt of Medical Science, Meeyannoor, Kollam",
    "B.J. MEDICAL COLLEGE, AHMEDABAD",
    "B.K.L. Walawalkar Rural Medical College, Ratnagiri",
    "B.R.D. MEDICAL COLLEGE, GORAKHPUR",
    "BAHIRAMJEE JIJIBHAI MEDICAL COLLGE, PUNE",
    "Banas Medical College and Research Institute, Palanpur, Gujarat",
    "BANGALORE MED. COLLEGE, BANGALORE",
    "Bangalore Medical College And Research Institute",
    "BANKURA SAMMILANI MED COLL, BANKURA",
    "BARASAT GOVERNMENT MEDICAL COLLEGE & HOSPITAL, WEST BENGAL",
    "Basaveswara Medical College and Hospital, Chitradurga",
    "BELGAUM INST. OF MEDICAL SCI., BELGAUM",
    "Believers Church Medical College Hospital, Thiruvalla, Kerala",
    "BGS Global Institute of Medical Sciences, Bangalore",
    "Bhaarat Medical College & Hospital",
    "Bharati Vidyapeeth Deemed University Medical College & Hospital, Sangli",
    "Bharati Vidyapeeth University Medical College, Pune",
    "Bhaskar Medical College, Yenkapally",
    "Bhima Bhoi Medical College And Hospital , Balangir",
    "BIDAR INSTITUTE OF MEDICAL SCI., BIDAR",
    "BPS Govt. Med. College, Sonepat",
    "BUNDELKHAND MEDICAL COLLEGE, SAGAR",
    "BURDWAN MEDICAL COLLEGE,BURDWAN",
    "C. Institute Of Medical Sciences, Chamarajanagar",
    "CALCUTTA NATIONAL MED COLL,KOLKATA",
    "Career Instt. Of Medical Sciences & Hospital, Lucknow",
    "Chalmeda Anand Rao Insttitute Of Medical Sciences, Karimnagar",
    "CHANDULAL CHANDRAKAR MEMORIAL GOVERNMENT MEDICAL COLLEGE, DURG",
    "Chandulal Chandrakar Memorial Medical College, Durg",
    "CHENGALPATTU MEDICAL COLL,CHENGALPATTU",
    "Chettinad Hospital & Research Institute, Kanchipuram",
    "CHHATTISGARH INSTITUTE OF MEDICAL SCIENCES, BILASP",
    "Chhindwara Institute Of Medical Sciences",
    "CHIKKABALLAPURA INSTITUTE OF MEDICAL SCIENCES, KARNATAKA",
    "CHIKKAMAGALURU INSTITUTE OF MEDICAL SCIENCES",
    "Chintpurni Medical College, Pathankot, Gurdaspur",
    "Chirayu Medical College and Hospital, Bairagarh,Bhopal",
    "Christian Medical College, Ludhiana",
    "Christian Medical College, Vellore",
    "COIMBATORE MEDICAL COLLEGE,COIMBATORE",
    "COLLEGE OF MEDICINE And JNM HOSPITAL, KALYANI,Cooch Behar",
    "CU Shah Medical College, Surendra Nagar",
    "Darbhanga Medical College, Laheriasarai",
    "Datta Meghe Medical College, Nagpur",
    "Dayanand Medical College & Hospital, Ludhiana",
    "Deben Mahata Government Medical College & Hospital",
    "Deccan College of Medical Sciences, Hyderabad",
    "Dhanalakshmi Srinivasan Medical College and Hospital, Perambalur",
    "Diamond Harbour Govt Medical College",
    "Diphu Medical College & Hospital, Assam",
    "DM Wayanad Institute of Medical Sciences, Wayanad, Kerala",
    "DNAPORE MEDICAL COLLEGE, MIDNAPUR",
    "Dr BR Ambedkar Medical College, Bangalore",
    "Dr Ram Manohar Lohia Inst. Of Med. Sce., Lucknow",
    "Dr. B.R. Ambedkar State Institute Of Medical Sciences",
    "Dr. B.S.A. Medical College, Delhi",
    "Dr. Chandramma Dayananda Sagar Instt. of Medical Education & Research, Harohalli, Hubli",
    "Dr. D Y Patil Medical College, Hospital and Research Centre, Pimpri, Pune",
    "Dr. D Y Patil Medical College, Kolhapur",
    "Dr. M.K. Shah Medical College & Research Centre, Ahmedabad",
    "Dr. N.D. Desai Faculty of Medical Science and Research, Nadiad",
    "Dr. P.S.I. Medical College , Chinoutpalli",
    "Dr. Panjabrao Alias Bhausaheb Deshmukh Memorial Medical College, Amravati",
    "Dr. Patnam Mahender Reddy Institute of Medical Sciences, Chevella, Rangareddy",
    "Dr. R. N. Cooper General Hospital, Juhu, Mumbai",
    "Dr. Somervel Memorial CSI Hospital & Medical College, Karakonam, Thiruvananthapuram",
    "Dr. Ulhas Patil Medical College & Hospital, Jalgaon",
    "DR. VAISHAMPAYAM MEMORIAL M.C., SHOLAPUR",
    "Dr. Vithalrao Vikhe Patil Foundations Medical College & Hospital, Ahmednagar",
    "Dr. VRK Womens Medical College, Aziznagar",
    "Dr. YS Parmar Govt. Medical College, Nahan",
    "Dr.Kiran C.Patel Medical College and Research Institute",
    "DR.RADHAKRISHNAN GOVERNMENT MEDICAL COLLEGE, HAMIRPUR",
    "DR.RAJENDRA PRASAD MC, TANDA",
    "DR.S.C.GOVT MEDICAL COLLEGE,,NANDED",
    "DR.S.N. MEDICAL COLLEGE, JODHPUR",
    "Dr.SS Tantia Medical College, Hospital and Research Center, Sriganganagar",
    "Dr.Vasantrao Pawar Med. Col. Hosp. & Research Centre, Nasik (Prev. NDMVP Samaj Medical College)",
    "East Point College of Medical Sciences & Research Centre, Bangalore",
    "Employees State Insurance Corporation Medical College",
    "Employees State Insurance Corporation Medical College, Alwar",
    "Era Lucknow Medical College , Lucknow",
    "ESIC MC, Gulbarga, Karnataka",
    "ESIC Medical College & Hospital, Bihta",
    "ESIC Medical College AND PGIMSR, Chennai",
    "ESIC Medical College, Faridabad",
    "ESIC Medical College, Gulbarga",
    "ESIC Medical College, Hyderabad",
    "ESIC PGIMSR, Joka, Kolkata, WB",
    "ESI-MC&PGIMS&R, Bangalore",
    "F.H. Medical College & Hospital, Etamdapur, Agra",
    "Faculty of Medicine and Health Sciences, Gurgaon (Formerly SGGST Medical College & R Centre, Gurgaon)",
    "Fakhruddin Ali Ahmed Medical College, Barpeta",
    "Father Mullers Medical College, Mangalore",
    "Fathima Instt. of Medical Sciences, Kadapa",
    "G.R. MEDICAL COLLEGE, GWALIOR",
    "G.S. Medical College & Hospital, Hapur, UP",
    "G.S.V.M. MEDICAL COLLEGE, KANPUR",
    "Gadag Institute Of Medical Sciences",
    "Gandhi Medical College Musheerabad Secunderabad",
    "GANDHI MEDICAL COLLEGE, BHOPAL",
    "Gautam Budh Chikitsa Mhavidyala",
    "Gayathri Vidya Parishad Institute of Health Care & Medical Technology, Visakhapatnam",
    "GCS Medical College, Ahmedabad",
    "Geetanjali Medical College & Hospital, Udaipur",
    "GHARWALE GOVT.MED SCI & RESEARCH, SRINAGAR",
    "Gian Sagar Medical College & Hospital, Patiala",
    "GITAM Institute of Medical Sciences and Research, Visakhapatnam",
    "GMC, Azamgarh, UP",
    "GMC, Bahraich",
    "GMC, Manjeri, Kerala",
    "GMC, Shahjhanpur",
    "GMERS Medical College, Morbi",
    "GMERS Medical College, Navsar",
    "GMERS Medical College, Panchmahal Godhra",
    "GMERS Medical College, Porbandar",
    "GMERS Medical College, Rajpipla",
    "GOA MEDICAL COLLEGE, PANAJI",
    "Gouri Devi Institute of Medical Sciences and Hospital, Durgapur",
    "GOVERMENT MC NANDURBAR MAHARARASTRA",
    "Goverment Medical College And Hospital Jalgaon",
    "Goverment Medical College, Bettiah",
    "Goverment Medical College, Datia",
    "Government Doon Medical College, Dehradun",
    "GOVERNMENT MC AND GENERAL HOSPITAL, SATARA",
    "GOVERNMENT MC AND HOSPITAL, CHANDIGARH",
    "Government Medcial College, Ambikapur",
    "Government Medcial College, Gondia",
    "Government Medical College & Hospital, Alibag-Raigad",
    "GOVERNMENT MEDICAL COLLEGE & HOSPITAL, JALPAIGURI",
    "GOVERNMENT MEDICAL COLLEGE AND HOSPITAL, CHANDIGARH",
    "GOVERNMENT MEDICAL COLLEGE AND HOSPITAL, KEONJHAR",
    "GOVERNMENT MEDICAL COLLEGE CHITTORGARH",
    "Government Medical College Hamirpur",
    "Government Medical College Khaleelwadi",
    "GOVERNMENT MEDICAL COLLEGE MAHASAMUND CHHATTISGARH",
    "Government Medical College Siddipet",
    "Government Medical College Suryapet",
    "GOVERNMENT MEDICAL COLLEGE, AKOLA",
    "Government Medical College, Ananthapuram",
    "Government Medical College, Anantnag",
    "GOVERNMENT MEDICAL COLLEGE, ANANTNAG J&K, VERINAG ROAD DIALGAM ANANTNAG, Jammu And Kashmir, 192210",
    "Government Medical College, Ariyalur",
    "Government Medical College, Banda",
    "Government Medical College, Baramulla",
    "GOVERNMENT MEDICAL COLLEGE, BHADRADRI, KOTHAGUDEM",
    "Government Medical College, Bharatpur",
    "Government Medical College, Bhilwara",
    "GOVERNMENT MEDICAL COLLEGE, CHURACHANDPUR",
    "GOVERNMENT MEDICAL COLLEGE, DHOLPUR",
    "Government Medical College, Dindigul",
    "Government Medical College, Doda",
    "Government Medical College, ESIC, Kollam",
    "GOVERNMENT MEDICAL COLLEGE, JAGTIAL",
    "Government Medical College, Kallakurichi",
    "Government Medical College, Kanker, Chhattisgarh",
    "Government Medical College, Kathua",
    "Government Medical College, Kollam",
    "GOVERNMENT MEDICAL COLLEGE, KONNI",
    "GOVERNMENT MEDICAL COLLEGE, KORBA(C.G.)",
    "Government Medical College, Krishnagiri",
    "GOVERNMENT MEDICAL COLLEGE, LATUR",
    "GOVERNMENT MEDICAL COLLEGE, MAHABUBABAD",
    "Government Medical College, Mahabubangar",
    "GOVERNMENT MEDICAL COLLEGE, MIRAJ",
    "Government Medical College, Nagapattinam",
    "GOVERNMENT MEDICAL COLLEGE, NAGARKURNOOL",
    "Government Medical College, Namakkal",
    "Government Medical College, Nilgiris",
    "Government Medical College, Omandurar",
    "GOVERNMENT MEDICAL COLLEGE, OSMANABAD",
    "Government Medical College, Pali",
    "GOVERNMENT MEDICAL COLLEGE, RAJNANDGAON",
    "Government Medical College, Rajnandgaon",
    "GOVERNMENT MEDICAL COLLEGE, RAJOURI",
    "Government Medical College, Ramanathapuram",
    "GOVERNMENT MEDICAL COLLEGE, SANGAREDDY",
    "GOVERNMENT MEDICAL COLLEGE, SINDHUDURG",
    "GOVERNMENT MEDICAL COLLEGE, SUNDARGARH",
    "GOVERNMENT MEDICAL COLLEGE, SURAT",
    "Government Medical College, Thiruvallur",
    "Government Medical College, Tiruppur",
    "Government Medical College, Virudhunagar",
    "Government Of Medical College And Hospital, Balasore",
    "Govt Institute Of Medcial Sciences Kasna",
    "Govt Medical College Badaun",
    "Govt Medical College Baramati",
    "Govt Medical College Barmer Rajasthan",
    "Govt Medical College Basti",
    "GOVT MEDICAL COLLEGE BUNDI, Rajasthan",
    "Govt Medical College Faizabad",
    "Govt Medical College Firozabad",
    "Govt Medical College Kannur",
    "Govt Medical College Nalgonda",
    "Govt Medical College Ratlam",
    "Govt Medical College Shahdol",
    "Govt Medical College Shivpuri",
    "Govt Medical College, Churu",
    "Govt Medical College, Dungarpur",
    "Govt Medical College, Ernakulam",
    "GOVT MEDICAL COLLEGE, IDUKKI",
    "Govt Medical College, Palakkad",
    "GOVT MEDICAL COLLEGE, WANAPARTHY",
    "GOVT. DHARAMAPURI MED COLL, DHARMAPURI",
    "GOVT. KILPAUK MEDICAL COLLEGE, CHENNAI",
    "Govt. Medical College And Hospital, Chandrapur",
    "Govt. Medical College ESI And Hospital, Coimbatore",
    "Govt. Medical College Karur",
    "GOVT. MEDICAL COLLEGE, JAMMU",
    "Govt. Medical College, Kannauj",
    "Govt. Medical College, Khandwa",
    "GOVT. MEDICAL COLLEGE, KOTTAYAM",
    "GOVT. MEDICAL COLLEGE, KOZHIKODE",
    "GOVT. MEDICAL COLLEGE, NAGPUR",
    "GOVT. MEDICAL COLLEGE, SIROHI (RAJASTHAN)",
    "Govt. Medical College, Srinagar",
    "Govt. Medical College, Udhampur",
    "GOVT. MEDICAL COLLEGE, AURANGABAD",
    "GOVT. MEDICAL COLLEGE, PATIALA",
    "GOVT. MEDICAL COLLEGE, TIRUNELVELI",
    "GOVT. MOHAN KUMARAMANGALAM M.C., SALEM",
    "Govt. Pudukkottai Medical College Hopt., Pudukkott",
    "Govt. Sivgangai M. C. Sivagangai",
    "GOVT. VELLORE MEDICAL COLLEGE, VELLORE",
    "GOVT.MEDICAL COLLEGE, AMRITSAR",
    "GOVT.MEDICAL COLLEGE, KOTA",
    "GOVT.MEDICAL COLLEGE, THRISSUR",
    "GOVT.MEDICAL COLLEGE,THIRUVANANTHAPURAM",
    "GRANT MEDICAL COLL & SIR J.J.HOSP,MUMBAI",
    "Great Eastern Medical School and Hospital, Srikakulam",
    "GSL Medical College, Rajahmundry",
    "GTMC, THIRUVARUR",
    "Gujarat Adani Institute of Medical Sciences, Bhuj",
    "Gulbarga Institute Of Medical Sciences, Gulbarga",
    "Gulbarga Institute of Medical Sciences, Gulbarga",
    "GUNTUR MEDICAL COLLEGE, GUNTUR",
    "GURU GOVIND SINGH MED COLL,FARIDKOT",
    "GUWAHATI MEDICAL COLLEGE, GUWAHATI",
    "GVMC, VILLUPURAM",
    "Hamdard Institute of Medical Sciences & Research, New Delhi",
    "HASSAN INST. MEDICAL SCIENCES, HASSAN",
    "HAVERI INSTITUTE OF MEDICAL SCIENCES, KARNATAKA",
    "HENGALPATTU MEDICAL COLL, CHENGALPATTU",
    "Heritage Institute of Medical Sciences, Varanasi",
    "Himalayan Institute of Medical Sciences, Dehradun",
    "Hind Institute of Medical Sciences, Barabanki",
    "Hind Institute of Medical Sciences, Sitapur",
    "Hi-Tech Medical College & Hospital, Bhubaneswar",
    "Hi-Tech Medical College & Hospital, Rourkela",
    "HOOTHUKUDI MEDICAL COLLEGE, THOOTHUKUDI",
    "ICARE Institute of Medical Sciences & Research, Haldia, Purba Midanpore",
    "IMS BHU, Varanasi, UP",
    "Index Medical College Hospital & Research Centre, Indore",
    "Indian Institute of Medical Science & Research, Jalna (Minority)",
    "INDIRA GANDHI GOVT. MEDICAL COLL., NAGPUR",
    "Indira Gandhi Institute Of Medical Sciences, Patna",
    "INDIRA GANDHI MEDICAL COLL., SHIMLA",
    "Indira Gandhi Medical College & RI, Puducherry",
    "Indira Medical College & Hospitals, Thiruvallur",
    "INST OF MED SCI & RESEARCH, SAIFAI",
    "INST OF PG MED EDU & RESEARCH, KOLKATA",
    "INST.OF MED.SCIENCES, BHU, VARANASI",
    "Instt. Of Medical Sciences & SUM Hospital, Bhubaneswar",
    "Integral Institute of Medical Sciences & Research, Lucknow",
    "IQ-City Medical College, Burdwan",
    "IRT Perundurai Medical College, Perundurai",
    "Jagannath Gupta Institute of Medical Sciences & Hospital, Kolkata",
    "Jaipur National University Institute of Medical Sciences and Research Centre, Jagatpura, Jaipur",
    "JANNAYAK KARPOORI THAKUR MEDICAL COLLEGE AND HOSPITAL, MADHEPURA,Jaunpur",
    "JAWAHAR LAL NEHRU MEDICAL, AJMER",
    "Jawaharlal Nehru Medical College, AMU, ALIGARH",
    "Jawaharlal Nehru Medical College, Belgaum",
    "Jawaharlal Nehru Medical College, Bhagalpur",
    "Jawaharlal Nehru Medical College, Sawangi (Meghe), Wardha",
    "JHALAWAR MEDICAL COLLEGE, Jhalawar",
    "JIPMER KARAIKAL",
    "JIPMER PUDUCHERRY",
    "JJM Medical College, Davangere",
    "JLN IMS, IMPHAL",
    "Jorhat Medical College And Hospital, JORHAT",
    "JSS Medical College, Mysore",
    "Jubilee Mission Medical College & Research Institute, Thrissur",
    "K S Hegde Medical Academy, Mangalore",
    "K V G Medical College, Sullia, Mangalore",
    "K.A.P. VISWANATHAM G.M.C., TIRUCHIRAPALLI",
    "K.D. Medical College Hospital & Research Centre, Mathura",
    "Kakatiya Medical College Warangal",
    "Kalinga Institute of Medical Sciences, Bhubaneswar",
    "Kalpana Chawla Govt. Medical College, Karnal",
    "Kamineni Academy of Medical Sciences & Research Center, Hyderabad",
    "Kamineni Institute of Medical Sciences, Narketpally",
    "Kanachur Institute of Medical Sciences, Mangalore",
    "Kannur Medical College, Kannur",
    "KANYAKUMARI GOVT. MED. COLL., ASARIPALLAM",
    "KARNATAK INST. OF MEDICAL SC., HUBLI",
    "Karpaga Vinayaga Institute of Medical Sciences, Maduranthagam",
    "Karpagam Faculty of Medical Sciences & Research, Coimbatore",
    "Karuna Medical College, Palakkad",
    "Karwar Institute Of Medical Sciences, Karwar",
    "Kasturba Medical College, Mangalore",
    "Kasturba Medical College, Manipal",
    "Katihar Medical College, Katihar",
    "Katuri Medical College, Guntur",
    "Kempegowda Institute of Medical Sciences, Bangalore",
    "KGMC, LUCKNOW",
    "Khaja Bandanawaz University - Faculty of Medical Sciences, Gulbarga",
    "KJ Somaiyya Medical College & Research Centre, Mumbai",
    "KMCH Institute of Health Sciences and Research, Coimbatore",
    "KMCT Medical College, Kozhikode, Calicut",
    "Kodagu Institute Of Medical Sciences, Kodagu",
    "Konaseema Institute of Medical Sciences & Research Foundation, Amalapuram",
    "Koppal Institute Of Medical Sciences",
    "KPC Medical College, Jadavpur, Kolkata",
    "Krishna Institute of Medical Sciences, Karad",
    "Krishna Mohan Medical College & Hospital, Mathura",
    "KURNOOL MEDICAL COLLEGE, KURNOOL",
    "L.L.R.M. MEDICAL COLLEGE, MEERUT",
    "L.L.R.M. MEDICAL COLLEGE, MEERUT",
    "L.N. Medical College and Research Centre, Bhopal",
    "Lady Hardinge Medical College, New Delhi",
    "LADY HARDINGE MEDICAL COLLEGE, NEW DELHI",
    "LAKHIMPUR MEDICAL COLLEGE, NORTH LAKHIMPUR, ASSAM",
    "LAWAR MEDICAL COLLEGE, Jhalawar",
    "LOKMANYA TILAK MUNICIPAL M C, MUMBAI",
    "LOKMANYA TILAK MUNICIPAL M C, MUMBAI",
    "Lord Buddha Koshi Medical College and Hospital, Saharsa",
    "Lt. B R K Government Medical College, Jagdalpur",
    "Lt. B R K Government Medical College, Jagdalpur",
    "Lt. L A M Govt. Medical College, Raigarh",
    "Lt. L A M Govt. Medical College, Raigarh",
    "M E S Medical College, Perintalmanna Malappuram Distt.Kerala",
    "M S Ramaiah Medical College, Bangalore",
    "M.G.M. MEDICAL COLLEGE, INDORE",
    "M.G.M. MEDICAL COLLEGE, INDORE",
    "M.G.M. MEDICAL COLLEGE, JAMSHEDPUR",
    "M.G.M. MEDICAL COLLEGE, JAMSHEDPUR",
    "M.P. SHAH MEDICAL COLLEGE, JAMNAGAR",
    "M.P. SHAH MEDICAL COLLEGE, JAMNAGAR",
    "Madha Medical College and Hospital, Thandalam, Chennai",
    "Madhubani Medical College, Madhubani",
    "MADRAS MEDICAL COLLEGE, CHENNAI",
    "MADRAS MEDICAL COLLEGE, CHENNAI",
    "MADURAI MEDICAL COLLEGE, MADURAI",
    "MADURAI MEDICAL COLLEGE, MADURAI",
    "Mahadevappa Rampure Medical College, Kalaburagi, Gulbarga",
    "Maharaja Agrasen Medical College, Agroha",
    "Maharaja Jitendra Narayan MC And Hospital",
    "MAHARAJA K.C. GAJAPATI M.C., BRAHMAPUR",
    "MAHARAJA K.C. GAJAPATI M.C., BRAHMAPUR",
    "Maharajah Institute of Medical Sciences, Vizianagaram",
    "MAHARANI LAXMI BAI MEDICAL COLL, JHANSI",
    "MAHARANI LAXMI BAI MEDICAL COLL, JHANSI",
    "MAHARANI LAXMI BAI MEDICAL COLL, JHANSI",
    "Maharashtra Institute of Medical Education & Research, Talegaon, Pune",
    "Maharashtra Institute of Medical Sciences & Research, Latur",
    "Maharishi Markandeshwar Institute Of Medical Sciences & Research, Mullana, Ambala",
    "Maharishi Markandeshwar Medical College & Hospital, Solan",
    "MAHARSHI DEVRAHA BABA AUTONOMOUSMC, DEORIA",
    "Mahatma Gandhi Institute of Medical Sciences, Sevagram, Wardha",
    "Mahatma Gandhi Medical College & Research Institute, Pondicherry",
    "Mahatma Gandhi Medical College and Hospital, Sitapur, Jaipur",
    "Mahatma Gandhi Missions Medical College, Aurangabad",
    "Mahatma Gandhi Missions Medical College, Navi Mumbai",
    "Mahaveer Institute of Medical Sciences & Research, Bhopal",
    "Mahavir Institute of Medical Sciences, Vikarabad, Telangana",
    "Maheshwara Medical College, Chitkul, Patancheru, Medak",
    "Malabar Medical College, Kozhikode, Calicut",
    "Malankara Orthodox Syrian Church Medical College, Kolenchery",
    "MALDA MED. COLLEGE, MALDA",
    "MALDA MED. COLLEGE, MALDA",
    "Malla Reddy Institute of Medical Sciences, Hyderabad",
    "Mallareddy Medical College for Women, Hyderabad",
    "Mamata Academy of Medical Sciences, Bachupally",
    "Mamata Medical College, Khammam",
    "MANDYA INST. OF MEDICAL SCI., MANDYA",
    "MANDYA INST. OF MEDICAL SCI., MANDYA",
    "Manipal Tata Medical College, Baridih Jameshedpur",
    "Mata Gujri Memorial Medical College, Kishanganj",
    "Maulana Azad Medical College, New Delhi",
    "MAULANA AZAD MEDICAL COLLEGE, NEW DELHI",
    "Mayo Institute of Medical Sciences, Barabanki",
    "MEDICAL COLLEGE, BARODA",
    "MEDICAL COLLEGE, BARODA",
    "MEDICAL COLLEGE, BHAVNAGAR",
    "MEDICAL COLLEGE, BHAVNAGAR",
    "MEDICAL COLLEGE, KOLKATA",
    "MEDICAL COLLEGE, KOLKATA",
    "Mediciti Institute Of Medical Sciences, Ghanpur",
    "MEDINIRAI MEDICAL COLLEGE (PREVIOUSLY KNOWN AS PALAMU MEDICAL COLLEGE), PALAMU",
    "Meenakshi Medical College and Research Institute, Enathur",
    "Melmaruvathur Adiparasakthi Instt. Medical Sciences and Research",
    "MG Inst. Of Medical Sciences, Sevagram Wardha",
    "MIDNAPORE MEDICAL COLLEGE, MIDNAPUR",
    "MNR Medical College & Hospital, Sangareddy",
    "MOGA INST. OF MEDICAL SCI., SHIMOGA",
    "MOTI LAL NEHRU MEDICAL COLL, ALLAHABAD",
    "MOTI LAL NEHRU MEDICAL COLL, ALLAHABAD",
    "Mount Zion Medical College, Chayalode, Ezhamkulam Adoor, Pathanamthitta",
    "MRA MEDICAL COLLEGE AMBEDKAR NAGAR, UP",
    "MRA MEDICAL COLLEGE AMBEDKAR NAGAR, UP",
    "Mursidabad M C & Hospital, Mursidabad",
    "Mursidabad M C & Hospital, Mursidabad",
    "Muzaffarnagar Medical College, Muzaffarnagar",
    "MVJ Medical College and Research Hospital, Bangalore",
    "MYSORE MED.& RESEARCH INST. MYSORE",
    "MYSORE MED.& RESEARCH INST. MYSORE",
    "N. K. P. Salve Instt. of Medical Sciences and Research Centre and Lata Mangeshkar Hospital, Nagpur",
    "N.C. Medical College & Hospital, Panipat",
    "NALANDA MEDICAL COLLEGE, PATNA",
    "NALANDA MEDICAL COLLEGE, PATNA",
    "Narayan Medical College & Hospital, Sasaram",
    "Narayana Medical College & Research Center, Kanpur (New)",
    "Narayana Medical College, Nellore",
    "National Capital Region Institute of Medical Sciences, Meerut",
    "National Institute of Medical Science & Research, Jaipur",
    "Navodaya Medical College, Raichur",
    "NDMC Medical College, Delhi",
    "NDMC Medical College, Delhi",
    "NEIGRIHMS, SHILLONG",
    "NEIGRIHMS, SHILLONG",
    "Netaji Subhas Medical College & Hospital, Amhara, Bihta, Patna",
    "NETAJI SUBHASH CHANDRA BOSE MC, JABALPUR",
    "NETAJI SUBHASH CHANDRA BOSE MC, JABALPUR",
    "NILRATAN SIRKAR MEDICAL COLLEGE, KOLKATA",
    "Nimra Institute of Medical Sciences, Krishna Dist., A.P.",
    "Noida International Institute Of Medical Sciences",
    "Nootan Medical College and Research Centre, Mehsana",
    "NORTH BENGAL MED. COLL, DARJEELING",
    "NORTH BENGAL MED. COLL, DARJEELING",
    "NRI Institute of Medical Sciences, Visakhapatnam",
    "NRI Medical College, Guntur",
    "Osmania Medical College Koti",
    "OVT. MEDICAL COLLEGE, PATIALA",
    "P E S Institute Of Medical Sciences and Research, Kuppam",
    "P K Das Institute of Medical Sciences, Palakkad, Kerala",
    "P. VISWANATHAM G.M.C.,TIRUCHIRAPALLI",
    "Pacific Institute of Medical Sciences, Umarda, Udaipur",
    "Pacific Medical College & Hospital, Bhilo Ka Bedla, Udaipur",
    "Padmashree Dr. D.Y.Patil Medical College, Navi Mumbai",
    "Panimalar Medical College Hospital & Research Institute, Chennai,Tamil Nadu",
    "Parul Institute of Medical Sciences & Research, Vadodara",
    "PATALIPUTRA MEDICAL COLLEGE, DHANBAD",
    "PATNA MEDICAL COLLEGE, PATNA",
    "Peoples College of Medical Sciences & Research Centre, Bhanpur, Bhopal",
    "PHULO JHANO MEDICAL COLLEGE , DUMKA",
    "PRAFULLA CHANDRA SEN GOVERNMENT MEDICAL COLLEGE & HOSPITAL, ARAMBAGH",
    "Prakash Institute of Medical Sciences & Research, Sangli",
    "Pramukhswami Medical College, Karmsad",
    "Prasad Institute of Medical Sciences, Lucknow",
    "Prathima Institute Of Medical Sciences, Karimnagar",
    "PSG Institute of Medical Sciences, Coimbatore",
    "PT. B.D. SHARMA PGIMS, ROHTAK",
    "Pt. D.D.U MEDICAL COLLEGE, RAJKOT",
    "Pt. J N M MEDICAL COLLEGE, RAIPUR",
    "Pt. Jawahar Lal Nehru Govt. Med. College, Chamba",
    "Pt. Raghunath Murmu Med. College, Baripada",
    "Puducherry Institute of Medical Sciences & Research, Pondicherry",
    "Punjab Institute of Medical Sciences, Jalandhar",
    "Pushpagiri Institute Of Medical Sciences and Research Centre, Tiruvalla",
    "R.G. KAR MEDICAL COLLEGE,KOLKATA",
    "R.N.T. MEDICAL COLLEGE, UDAIPUR",
    "R.V.M. Institute of Medical Sciences and Research Centre, Siddipet",
    "RAICHUR INST. OF MEDICAL SCI., RAICHUR",
    "Raiganj Government Medical College",
    "Raipur Institute of Medical Sciences (RIMS), Raipur",
    "Rajah Muthiah Medical College, Annamalai Universit",
    "Rajarajeswari Medical College & Hospital, Bangalore",
    "Rajarshee Chhatrapati Shahu Maharaj GMC Kolhapur",
    "RAJENDRA INST. OF MED. SCI., RANCHI",
    "RAJIV GANDHI IMS, KADAPA",
    "Rajkiya Medical College, Jalaun",
    "RAJMATA SHRIMATI DEVENDRA KUMARI SINGHDEO GOVERNMENT MEDICAL COLLEGE, AMBIKAPUR,SURGUJA",
    "Rajshree Medical Research Institute, Bareilly",
    "Rama Medical College and Hospital , Kanpur",
    "Rama Medical College Hospital and Research Centre, Hapur",
    "RAMPURHAT GOVT MEDICAL COLLEGE RAMPURHAT",
    "Rangaraya Medical College, Kakinada",
    "Rani Durgavati Medical College, Banda",
    "RATAN SIRKAR MEDICAL COLLEGE, KOLKATA",
    "RCSMGMC, KOLHAPUR",
    "RDJM Medical College & Hospital, Turki, Muzaffarpur",
    "RDWAN MEDICAL COLLEGE,BURDWAN",
    "REGIONAL INST OF MEDICAL SCI, IMPHAL",
    "RIMS Srikakulam",
    "RKDF Medical College Hospital & Research Centre, Jatkhedi, Bhopal",
    "Rohilkhand Medical College & Hospital, Bareilly",
    "RU GOVIND SINGH MED COLL,FARIDKOT",
    "RUHS College Of Medical Sciences, Jaipur",
    "Rural Medical College, Loni",
    "Ruxmaniben Deepchand Gardi Medical College, Ujjain",
    "S S Institute of Medical Sciences& Research Centre, Davangere",
    "S V S Medical College, Mehboobnagar",
    "S. Nijalingappa Medical College & HSK Hospital & Research Centre, Bagalkot",
    "S.C.B. MEDICAL COLLEGE, CUTTACK",
    "S.M.S. MEDICAL COLLEGE, JAIPUR",
    "S.N. MEDICAL COLLEGE, AGRA",
    "S.S. MEDICAL COLLEGE, REWA",
    "Sagar Dutta Medical College & Hospital, Kolkata",
    "Saheed Laxman Nayak Med. College And Hos., Koraput",
    "SAHEED LAXMAN NAYAK MED. COLLEGE AND HOS., KORAPUT",
    "Sambharam Institute of Medical Sciences & Research, Kolar",
    "Santhiram Medical College, Nandyal",
    "Santiniketan Medical College, Bolpur, West Bengal",
    "Santosh Medical College, Ghaziabad",
    "Sapthagiri Institute of Medical Sciences & Research Centre, Bangalore",
    "Saraswati Institute of Medical Sciences, Hapur",
    "Saraswati Medical College, Unnao, U.P.",
    "SARAT CHANDRA CHATTOPADHYAY GOVT. MEDICAL COLLEGE & HOSPITAL, ULUBERIA",
    "SARDAR PATEL MEDICAL COLLEGE, BIKANER",
    "Saveetha Medical College and Hospital, Kanchipuram",
    "SBKS Medical Instt. & Research Centre, Vadodra",
    "School of Medical Sciences & Research,Greater Noida",
    "SDM College of Medical Sciences & Hospital, Sattur, Dharwad",
    "SETH G.S. MEDICAL COLLEGE, MUMBAI",
    "SH VASANT RAO NAIK GOVT.M.C.,YAVATMAL",
    "Sh. Lal Bahadur Shastri Govt. Med. College. Mandi",
    "Shadan Institute of Medical Sciences,Research Centre and Teaching Hospital, Peerancheru",
    "Shaheed Nirmal Mahto Medical College & Hospital, Dhanbad",
    "Shantabaa Medical College, Amreli",
    "SHEIKH BHIKHARI MEDICAL COLLEGE & HOSPITAL, HAZARIBAG",
    "SHIMOGA INST. OF MEDICAL SCI., SHIMOGA",
    "SHKM GMC, Nalhar, Mewat, Haryana",
    "SHRI ATAL BIHARI VAJPAYEE GOVERNMENT MEDICAL COLLEGE, CHHAINSA, FARIDABAD",
    "Shri Atal Bihari Vajpayee MC & Research Institute, Bengaluru",
    "Shri B M Patil Medical College, Hospital & Research Centre, Vijayapura(Bijapur",
    "Shri Balaji Institute Of Medical Science",
    "SHRI BHAUSAHEB HIRE GOVT. M.C., DHULE",
    "Shri Guru Ram Rai Institute of Medical & Health Sciences, Dehradun",
    "SHRI KALYAN GOVT MEDICAL COLLEGE SIKAR",
    "Shri Ram Murti Smarak Institute of Medical Sciences, Bareilly",
    "Shri Ramkrishna Institute of Medical Sciences & Sanaka Hospitals, Durgapur",
    "Shri Sathya Sai Medical College and Research Institute, Kancheepuram",
    "Shri Shankaracharya Institute of Medical Sciences, Bhilai",
    "Shri Vinobha Bhave Institute Medical Sciences",
    "Shridevi Institute of Medical Sciences & Research Hospital, Tumkur",
    "Siddartha Medical College, Vijayawada",
    "Sikkim Manipal Institute of Medical Sciences, Gangtok",
    "SILCHAR MEDICAL COLLEGE, SILCHER",
    "Sindhudurg Shikshan Prasarak Mandal (SSPM) Medical College & Lifetime Hospital, Padave, Sindhudurg",
    "SI-PGIMSR, Chennai, TN",
    "SKIMS MEDICAL COLLEGE, BEMINA, SRINAGAR",
    "SLBS Govt. Medical College, Mandi",
    "SMBT Institute of Medical Sciences & Research Centre, Nandihills, Nashik",
    "Smt. Kashibai Navale Medical College and General Hospital,Pune",
    "SOBAN SINGH JEENA GOVERNMENT INSTITUTE OF MEDICAL SCIENCE & RESEARCH, ALMORA",
    "Sree Balaji Medical College and Hospital, Chennai",
    "Sree Gokulam Medical College Trust & Research Foundation, Trivandrum",
    "Sree Mookambika Institute of Medical Sciences, Kanyakumari",
    "Sree Narayana Instt. of Medical Sciences, Chalakka,Ernakulam",
    "Sree Uthradom Thiurnal Academy of Medical Sciences,Trivandrum",
    "Sri Aurobindo Medical College and Post Graduate Institute , Indore",
    "Sri Devaraj URS Medical College, Kolar",
    "Sri Guru Ram Das Institute of Medical Sciences and Research, Sri Amritsar",
    "Sri Jagannath Medical College & Hospital, Puri",
    "SRI KRISHNA MEDICAL COLLEGE, MUZAFFARPUR",
    "Sri Lakshmi Narayana Institute of Medical Sciences, Pondicherry",
    "Sri Manakula Vinayagar Medical College & Hospital, Pondicherry",
    "Sri Muthukumaran Medical College,Chennai",
    "Sri Ramachandra Medical College & Research Institute, Chennai",
    "Sri siddhartha Institute of Medical Sciences & Research Centre, Bangalore",
    "Sri Siddhartha Medical College, Tumkur",
    "Sri Venkateswara Medical College, Tirupati",
    "Sri Venkateswaraa Medical College, Hospital & Research Centre, Pondicherry",
    "Srinivas Institute of Medical Research Centre, Srinivasnagar, Mangalore",
    "SRM Medical College Hospital & Research Centre, Chengalpattu",
    "St. Johns Medical College, Bangalore",
    "STANLEY MEDICAL COLLEGE, CHENNAI",
    "Subbaiah Institute of Medical Sciences, Shimoga, Karnataka",
    "Subharti Medical College, Meerut",
    "SUH Maulana Mahmood Hasan Medical College, Saharanpur",
    "Surabhi Institute of Medical Sciences, Siddipet, Telangana",
    "SVIMS - Sri Padmavathi Medical College For Women, Tirupati",
    "SWAMI RAMANAND Tirth RURAL M.C,AMBAJOGAI",
    "Symbiosis Medical College for Women, Pune",
    "T S Misra Medical College & Hospital, Amusi, Lucknow",
    "T.D. MEDICAL COLLEGE, ALLAPPUZHA",
    "Tagore Medical College and Hospital, Chennai",
    "TAMRALIPTO GOVERNMENT MEDICAL COLLEGE & HOSPITAL, WEST BENGAL",
    "TARANCHAL F HOSP TRUST MC,HALDWANI",
    "Teerthanker Mahaveer Medical College, Moradabad",
    "Terna Medical College, Navi Mumbai",
    "Tezpur Medical College, Tezpur",
    "TH G.S. MEDICAL COLLEGE, MUMBAI",
    "THANJAVUR MEDICAL COLL.,THANJAVUR",
    "The Oxford Medical College, Hospital & Research Centre, Bangalore",
    "THENI GOVT. MEDICAL COLLEGE, THENI",
    "Thiruvannamalai MC, Thiruvannamalai, TN",
    "THOOTHUKUDI MEDICAL COLLEGE,THOOTHUKUDI",
    "Tomo Riba Institute Health And MS, Naharlagun",
    "TOPIWALA NATIONAL MEDICAL COLLEGE,MUMBAI",
    "Travancore Medical College, Kollam",
    "Trichy SRM Medical College Hospital & Research Centre, Trichy",
    "Tripura Medical College and Dr. B R A M Teaching Hospital, Agartala",
    "TRR Institute of Medical Sciences, Patancheru",
    "United Institute of Medical Sciences, Allahabad",
    "University College of Medical Sciences, Delhi",
    "Uttar Pradesh University Of Medical Sciences, Saifai, Etawah",
    "V.S.S. MEDICAL COLLEGE, BURLA",
    "VARDHMAN INSTITUTE OF MEDICAL SCIENCES, NALANDA",
    "Vardhman Mahavir MC & Safdarjung Hospital New Delhi, VMMC",
    "Varun Arjun Medical College, Banthra, Shahjahanpur",
    "Vedantaa Institute of Medical Sciences, Palghar, Maharashtra",
    "Velammal Medical College Hospital and Research Institute, Madurai",
    "Venkateshwara Institute of Medical Sciences, Gajraula",
    "VERNMENT MEDICAL COLLEGE, MIRAJ",
    "VIJAYNAGAR INST OF MED. SC,BELLARY",
    "Vinayaka Missions Kirupananda Variyar Medical College, Salem",
    "Vinayaka Missions Medical College, Karaikal, Pondicherry",
    "Viswabharathi Medical College, Kurnool",
    "VMMC AND SAFDARJUNG HOSPITAL, NEW DELHI",
    "VT. MEDICAL COLLEGE, NAGPUR",
    "Vydehi Institute Of Medical Sciences & Research Centre, Bangalore",
    "World College of Medical Sciences & Research, Jhajjar, Haryana",
    "YADGIRI INSTITUTE OF MEDICAL SCIENCES, YADGIRI",
    "Yenepoya Medical College, Mangalore",
    "ZORAM MEDICAL COLLEGE Falkawn",
    "Zydus Medical College & Hospital, Dahod"
  ];

  @override
  void dispose() {
    _universityController.dispose();
    super.dispose();
  }

  Widget buildRadioOption(String value) {
    return Row(
      children: [
        Radio<String>(
          activeColor: mainBlue,
          value: value,
          groupValue: academicYear,
          onChanged: (val) => setState(() => academicYear = val),
        ),
        Text(value, style: radioTextStyle),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        title: const Text("Bsc MLT", style: appBarText),
        backgroundColor: mainBlue,
      ),
      body: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 20),
        child: ListView(
          children: [
            const SizedBox(height: 50),
            const Align(
              alignment: Alignment.centerLeft,
              child: Text(
                'Choose Your Current Year',
                style: TextStyle(fontSize: 20.0, fontWeight: FontWeight.w500),
              ),
            ),
            const SizedBox(height: 15),
            Wrap(
              spacing: 50,
              runSpacing: 10,
              children: academicYears.map(buildRadioOption).toList(),
            ),
            const SizedBox(height: 30),
            const Align(
              alignment: Alignment.centerLeft,
              child: Text(
                'University of Education',
                style: TextStyle(fontSize: 20.0, fontWeight: FontWeight.w500),
              ),
            ),
            const SizedBox(height: 15),
            DropdownMenu<String>(
              controller: _universityController,
              requestFocusOnTap: true,
              enableSearch: true,
              enableFilter: true,
              keyboardType: TextInputType.text,
              menuStyle: const MenuStyle(
                padding: WidgetStatePropertyAll(EdgeInsets.symmetric(horizontal: 20)),
                fixedSize: WidgetStatePropertyAll(Size.fromHeight(360)),
              ),
              hintText: 'Select University of Education',
              textStyle: hintStyle,
              onSelected: (value) => setState(() => _university = value),
              dropdownMenuEntries: universities
                  .toSet()
                  .toList()
                  .map((university) => DropdownMenuEntry(value: university, label: university))
                  .toList(),
            ),
          ],
        ),
      ),
      bottomNavigationBar: ElevatedButton(
        onPressed: () {
          FocusScope.of(context).unfocus(); // Hide keyboard
          if (_university != null && academicYear != null) {
            Navigator.pushNamed(context, '/County_that_you_preferred_page');
          } else {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content: Text('Please select both your current year and university.'),
                backgroundColor: Colors.red,
              ),
            );
          }
        },
        style: ButtonStyle(
          padding: const WidgetStatePropertyAll(EdgeInsets.all(15)),
          backgroundColor: const WidgetStatePropertyAll(mainBlue),
          shape: WidgetStatePropertyAll(
            RoundedRectangleBorder(borderRadius: BorderRadius.circular(0)),
          ),
        ),
        child: const Text(
          'Continue',
          style: TextStyle(fontSize: 20.0, color: Colors.white),
        ),
      ),
    );
  }
}

